// AUTO-GENERATED by scripts/sync_project.py — do not edit by hand.
// Source: project.config.json

export const PROJECT_ID = "wc-2026-3110f";
export const FUNCTIONS_REGION = "us-central1";
export const ANDROID_PACKAGE = "com.techmomentum.wc2026";

export const DATA_CONNECT_SERVICE_ID = "wc-2026-3110f-service";
export const DATA_CONNECT_LOCATION = "us-east4";
export const DATA_CONNECT_INSTANCE_ID = "wc-2026-3110f-instance";
export const DATA_CONNECT_DATABASE = "wc-2026-3110f-database";

export const STICKERS_PER_PACK = 5;
export const SIGNUP_FREE_PACKS = 2;
export const LOGIN_REWARD_PACKS = 1;
export const LOGIN_REWARD_INTERVAL_HOURS = 24;
export const REWARDED_AD_STICKERS = 2;
export const REWARDED_AD_COOLDOWN_MINUTES = 60;
export const DAILY_FREE_PACKS = 0;
export const DAILY_REWARDED_PACK_LIMIT = 0;
export const DAILY_FREE_SLOT_SPINS = 10;
export const REWARDED_SLOT_SPINS = 5;
export const REWARDED_SLOT_SPIN_COOLDOWN_MINUTES = 60;
export const DAILY_SLOT_PACK_REWARD_CAP = 5;
export const SWAP_DUPLICATES_FOR_PACK = 5;
export const TOTAL_TEAMS = 48;
export const PLAYERS_PER_TEAM = 26;
export const TOTAL_STICKERS = 1296;

export const EMULATOR_PORTS = {
  auth: 9099,
  functions: 5001,
  firestore: 8080,
  storage: 9199,
  dataconnect: 9399,
} as const;
