/** EXTRA_SQUADS from generate_seed_data.py + full squads for remaining WC teams. */
export const EXTENDED = {
  netherlands: [
    [1, "Bart Verbruggen", "Goalkeeper", "rare"],
    [2, "Denzel Dumfries", "Defender", "epic"],
    [3, "Matthijs de Ligt", "Defender", "epic"],
    [4, "Frenkie de Jong", "Midfielder", "legendary"],
    [5, "Nathan Aké", "Defender", "rare"],
    [6, "Steven Bergwijn", "Forward", "rare"],
    [7, "Memphis Depay", "Forward", "epic"],
    [8, "Cody Gakpo", "Forward", "epic"],
    [9, "Brian Brobbey", "Forward", "rare"],
    [10, "Wout Weghorst", "Forward", "rare"],
    [11, "Steven Berghuis", "Midfielder", "common"],
    [12, "Jeremie Frimpong", "Defender", "rare"],
    [13, "Daley Blind", "Defender", "common"],
    [14, "Georginio Wijnaldum", "Midfielder", "rare"],
    [15, "Mark Flekken", "Goalkeeper", "common"],
  ],
  belgium: [
    [1, "Thibaut Courtois", "Goalkeeper", "legendary"],
    [2, "Thomas Meunier", "Defender", "common"],
    [3, "Arthur Theate", "Defender", "rare"],
    [4, "Youri Tielemans", "Midfielder", "epic"],
    [5, "Jan Vertonghen", "Defender", "rare"],
    [6, "Axel Witsel", "Midfielder", "rare"],
    [7, "Jeremy Doku", "Forward", "epic"],
    [8, "Romelu Lukaku", "Forward", "legendary"],
    [9, "Loïs Openda", "Forward", "epic"],
    [10, "Kevin De Bruyne", "Midfielder", "legendary"],
    [11, "Amadou Onana", "Midfielder", "rare"],
    [12, "Timothy Castagne", "Defender", "common"],
    [13, "Charles De Ketelaere", "Midfielder", "rare"],
    [14, "Dodi Lukebakio", "Forward", "common"],
    [15, "Koen Casteels", "Goalkeeper", "rare"],
  ],
  croatia: [
    [1, "Dominik Livaković", "Goalkeeper", "epic"],
    [2, "Josip Šutalo", "Defender", "rare"],
    [3, "Joško Gvardiol", "Defender", "legendary"],
    [4, "Marcelo Brozović", "Midfielder", "epic"],
    [5, "Borna Sosa", "Defender", "common"],
    [6, "Luka Modrić", "Midfielder", "legendary"],
    [7, "Bruno Petković", "Forward", "rare"],
    [8, "Mateo Kovačić", "Midfielder", "epic"],
    [9, "Andrej Kramarić", "Forward", "epic"],
    [10, "Luka Sucic", "Midfielder", "rare"],
    [11, "Marko Livaja", "Forward", "common"],
    [12, "Mislav Oršić", "Forward", "common"],
    [13, "Nikola Vlašić", "Midfielder", "rare"],
    [14, "Ivan Perišić", "Forward", "epic"],
    [15, "Ivica Ivusić", "Goalkeeper", "common"],
  ],
  japan: [
    [1, "Daniel Schmidt", "Goalkeeper", "common"],
    [2, "Hiroki Ito", "Defender", "rare"],
    [3, "Shogo Taniguchi", "Defender", "common"],
    [4, "Wataru Endo", "Midfielder", "epic"],
    [5, "Takehiro Tomiyasu", "Defender", "rare"],
    [6, "Kaoru Mitoma", "Forward", "epic"],
    [7, "Takumi Minamino", "Forward", "rare"],
    [8, "Ritsu Doan", "Forward", "rare"],
    [9, "Ayase Ueda", "Forward", "common"],
    [10, "Takuma Asano", "Forward", "rare"],
    [11, "Junya Ito", "Forward", "epic"],
    [12, "Daizen Maeda", "Forward", "common"],
    [13, "Reo Hatate", "Midfielder", "common"],
    [14, "Ao Tanaka", "Midfielder", "rare"],
    [15, "Shuichi Gonda", "Goalkeeper", "common"],
  ],
  colombia: [
    [1, "David Ospina", "Goalkeeper", "epic"],
    [2, "Santiago Arias", "Defender", "common"],
    [3, "Davinson Sánchez", "Defender", "epic"],
    [4, "Wilmar Barrios", "Midfielder", "rare"],
    [5, "Yerry Mina", "Defender", "rare"],
    [6, "James Rodríguez", "Midfielder", "legendary"],
    [7, "Luis Díaz", "Forward", "legendary"],
    [8, "Jefferson Lerma", "Midfielder", "rare"],
    [9, "Radamel Falcao", "Forward", "epic"],
    [10, "Juan Cuadrado", "Midfielder", "epic"],
    [11, "Luis Sinisterra", "Forward", "rare"],
    [12, "Jhon Arias", "Forward", "common"],
    [13, "John Lucumí", "Defender", "rare"],
    [14, "Sebastián Villa", "Forward", "common"],
    [15, "Camilo Vargas", "Goalkeeper", "common"],
  ],
  uruguay: [
    [1, "Sergio Rochet", "Goalkeeper", "rare"],
    [2, "José Giménez", "Defender", "epic"],
    [3, "Diego Godín", "Defender", "rare"],
    [4, "Federico Valverde", "Midfielder", "legendary"],
    [5, "Matías Viña", "Defender", "common"],
    [6, "Rodrigo Bentancur", "Midfielder", "epic"],
    [7, "Darwin Núñez", "Forward", "epic"],
    [8, "Giorgian Arrascaeta", "Midfielder", "epic"],
    [9, "Luis Suárez", "Forward", "legendary"],
    [10, "Facundo Pellistri", "Forward", "common"],
    [11, "Ronald Araújo", "Defender", "epic"],
    [12, "Nicolás de la Cruz", "Midfielder", "rare"],
    [13, "Brian Rodríguez", "Forward", "common"],
    [14, "Manuel Ugarte", "Midfielder", "rare"],
    [15, "Fernando Muslera", "Goalkeeper", "rare"],
  ],
  senegal: [
    [1, "Édouard Mendy", "Goalkeeper", "epic"],
    [2, "Youssouf Sabaly", "Defender", "common"],
    [3, "Kalidou Koulibaly", "Defender", "legendary"],
    [4, "Idrissa Gueye", "Midfielder", "epic"],
    [5, "Abdou Diallo", "Defender", "rare"],
    [6, "Sadio Mané", "Forward", "legendary"],
    [7, "Ismaïla Sarr", "Forward", "epic"],
    [8, "Cheikhou Kouyaté", "Midfielder", "rare"],
    [9, "Boulaye Dia", "Forward", "rare"],
    [10, "Mame Boussuf Lô", "Forward", "common"],
    [11, "Pape Matar Sarr", "Midfielder", "rare"],
    [12, "Formose Mendy", "Defender", "common"],
    [13, "Nicolas Jackson", "Forward", "epic"],
    [14, "Pathé Ciss", "Midfielder", "common"],
    [15, "Seny Dieng", "Goalkeeper", "common"],
  ],
  morocco: [
    [1, "Yassine Bounou", "Goalkeeper", "epic"],
    [2, "Achraf Hakimi", "Defender", "legendary"],
    [3, "Nayef Aguerd", "Defender", "rare"],
    [4, "Sofyan Amrabat", "Midfielder", "epic"],
    [5, "Romain Saïss", "Defender", "rare"],
    [6, "Hakim Ziyech", "Midfielder", "epic"],
    [7, "Youssef En-Nesyri", "Forward", "epic"],
    [8, "Azzedine Ounahi", "Midfielder", "rare"],
    [9, "Abde Ezzalzouli", "Forward", "rare"],
    [10, "Sofiane Boufal", "Forward", "rare"],
    [11, "Brahim Díaz", "Forward", "epic"],
    [12, "Selim Amallah", "Midfielder", "common"],
    [13, "Yahya Attiat-Allah", "Defender", "common"],
    [14, "Zakaria Aboukhlal", "Forward", "common"],
    [15, "Munir El Kajoui", "Goalkeeper", "common"],
  ],
  algeria: [
    [1, "Raïs M'Bohli", "Goalkeeper", "rare"],
    [2, "Youcef Atal", "Defender", "rare"],
    [3, "Ramy Bensebaini", "Defender", "epic"],
    [4, "Ismaël Bennacer", "Midfielder", "epic"],
    [5, "Aïssa Mandi", "Defender", "rare"],
    [6, "Riyad Mahrez", "Forward", "legendary"],
    [7, "Youcef Belaïli", "Midfielder", "rare"],
    [8, "Adam Ounas", "Midfielder", "common"],
    [9, "Baghdad Bounedjah", "Forward", "rare"],
    [10, "Islam Slimani", "Forward", "epic"],
    [11, "Farès Chaïbi", "Midfielder", "rare"],
    [12, "Haris Belkebla", "Midfielder", "common"],
    [13, "Ramiz Zerrouki", "Midfielder", "common"],
    [14, "Jaouad Zaid", "Defender", "common"],
    [15, "Anthony Mandrea", "Goalkeeper", "common"],
  ],
  south_africa: [
    [1, "Ronwen Williams", "Goalkeeper", "rare"],
    [2, "Khuliso Khumalo", "Defender", "common"],
    [3, "Grant Kekana", "Defender", "common"],
    [4, "Themba Zwane", "Midfielder", "epic"],
    [5, "Mothobi Mvala", "Defender", "rare"],
    [6, "Sphephelo Sithole", "Midfielder", "common"],
    [7, "Percy Tau", "Forward", "epic"],
    [8, "Teboho Mokoena", "Midfielder", "rare"],
    [9, "Evidence Makgopa", "Forward", "common"],
    [10, "Lyle Foster", "Forward", "legendary"],
    [11, "Zakhele Lepasa", "Forward", "rare"],
    [12, "Thapelo Maseko", "Forward", "common"],
    [13, "Tebogo Moerane", "Midfielder", "common"],
    [14, "Mosa Lebusa", "Defender", "common"],
    [15, "Veli Mothwa", "Goalkeeper", "common"],
  ],
  south_korea: [
    [1, "Kim Seung-gyu", "Goalkeeper", "rare"],
    [2, "Kim Min-jae", "Defender", "legendary"],
    [3, "Kim Young-gwon", "Defender", "rare"],
    [4, "Jung Woo-young", "Midfielder", "epic"],
    [5, "Kim Jin-su", "Defender", "common"],
    [6, "Son Heung-min", "Forward", "legendary"],
    [7, "Lee Kang-in", "Midfielder", "epic"],
    [8, "Hwang Hee-chan", "Forward", "rare"],
    [9, "Cho Gue-sung", "Forward", "rare"],
    [10, "Hwang Ui-jo", "Forward", "epic"],
    [11, "Jeong Woo-yeong", "Midfielder", "rare"],
    [12, "Hong Hyun-seok", "Midfielder", "common"],
    [13, "Lee Jae-sung", "Midfielder", "common"],
    [14, "Kim Tae-hwan", "Defender", "common"],
    [15, "Jo Hyeon-woo", "Goalkeeper", "common"],
  ],
  czechia: [
    [1, "Tomáš Vaclík", "Goalkeeper", "rare"],
    [2, "Vladimír Coufal", "Defender", "common"],
    [3, "Ondřej Kúdela", "Defender", "rare"],
    [4, "Tomáš Souček", "Midfielder", "epic"],
    [5, "David Jurásek", "Defender", "common"],
    [6, "Antonín Barák", "Midfielder", "rare"],
    [7, "Patrik Schick", "Forward", "legendary"],
    [8, "Alex Král", "Midfielder", "common"],
    [9, "Jan Kuchta", "Forward", "rare"],
    [10, "Michal Sadílek", "Midfielder", "epic"],
    [11, "Adam Hložek", "Forward", "rare"],
    [12, "Lukáš Provod", "Midfielder", "common"],
    [13, "Ladislav Krejčí", "Defender", "common"],
    [14, "Tomáš Holeš", "Midfielder", "common"],
    [15, "Jiří Pavlenka", "Goalkeeper", "common"],
  ],
  switzerland: [
    [1, "Yann Sommer", "Goalkeeper", "epic"],
    [2, "Manuel Akanji", "Defender", "epic"],
    [3, "Nico Elvedi", "Defender", "rare"],
    [4, "Granit Xhaka", "Midfielder", "legendary"],
    [5, "Fabian Schär", "Defender", "rare"],
    [6, "Xherdan Shaqiri", "Midfielder", "epic"],
    [7, "Breel Embolo", "Forward", "epic"],
    [8, "Ruben Vargas", "Forward", "rare"],
    [9, "Dan Ndoye", "Forward", "rare"],
    [10, "Michel Rieder", "Midfielder", "common"],
    [11, "Steven Zuber", "Midfielder", "rare"],
    [12, "Silvan Widmer", "Defender", "common"],
    [13, "Denis Zakaria", "Midfielder", "rare"],
    [14, "Zeki Amdouni", "Forward", "common"],
    [15, "Gregor Kobel", "Goalkeeper", "rare"],
  ],
  qatar: [
    [1, "Saad Al Sheeb", "Goalkeeper", "rare"],
    [2, "Ró-Ró", "Defender", "common"],
    [3, "Abdelkarim Hassan", "Defender", "rare"],
    [4, "Hassan Al Haydos", "Midfielder", "epic"],
    [5, "Boualem Khoukhi", "Defender", "rare"],
    [6, "Akram Afif", "Forward", "legendary"],
    [7, "Almoez Ali", "Forward", "epic"],
    [8, "Karim Boudiaf", "Midfielder", "common"],
    [9, "Mohammed Muntari", "Forward", "rare"],
    [10, "Tarek Salman", "Defender", "common"],
    [11, "Abdulaziz Hatem", "Midfielder", "rare"],
    [12, "Yousuf Abdurisag", "Forward", "common"],
    [13, "Homam Ahmed", "Defender", "common"],
    [14, "Jassem Abdulsallan", "Midfielder", "common"],
    [15, "Mishal Barsham", "Goalkeeper", "common"],
  ],
  bosnia_herzegovina: [
    [1, "Asmir Begović", "Goalkeeper", "rare"],
    [2, "Sead Kolašinac", "Defender", "epic"],
    [3, "Ermin Bičakčić", "Defender", "common"],
    [4, "Miralem Pjanić", "Midfielder", "legendary"],
    [5, "Stojan Vukanović", "Defender", "common"],
    [6, "Gojko Cimirot", "Midfielder", "rare"],
    [7, "Edin Džeko", "Forward", "legendary"],
    [8, "Amar Kadić", "Midfielder", "common"],
    [9, "Miroslav Stevanović", "Forward", "rare"],
    [10, "Marko Arnautović", "Forward", "epic"],
    [11, "Elvis Mešić", "Midfielder", "common"],
    [12, "Benjamin Tahirović", "Midfielder", "rare"],
    [13, "Anel Ahmedhodžić", "Defender", "rare"],
    [14, "Adrian Leon Bagić", "Defender", "common"],
    [15, "Ibrahim Šehić", "Goalkeeper", "common"],
  ],
  scotland: [
    [1, "Angus Gunn", "Goalkeeper", "rare"],
    [2, "Kieran Tierney", "Defender", "epic"],
    [3, "Grant Hanley", "Defender", "common"],
    [4, "Scott McTominay", "Midfielder", "epic"],
    [5, "John Souttar", "Defender", "rare"],
    [6, "Andy Robertson", "Defender", "legendary"],
    [7, "John McGinn", "Midfielder", "epic"],
    [8, "Callum McGregor", "Midfielder", "rare"],
    [9, "Che Adams", "Forward", "rare"],
    [10, "Lyndon Dykes", "Forward", "common"],
    [11, "Ryan Christie", "Midfielder", "rare"],
    [12, "Lewis Morgan", "Forward", "common"],
    [13, "Billy Gilmour", "Midfielder", "rare"],
    [14, "Jack Hendry", "Defender", "common"],
    [15, "Zander Clark", "Goalkeeper", "common"],
  ],
  haiti: [
    [1, "Johny Placide", "Goalkeeper", "rare"],
    [2, "Derrick Etienne", "Defender", "common"],
    [3, "Mechack Jérôme", "Defender", "rare"],
    [4, "Zachary Brault-Guillard", "Defender", "common"],
    [5, "Ricardo Adé", "Defender", "rare"],
    [6, "Derrick Etienne Jr", "Midfielder", "epic"],
    [7, "Mondy Prunier", "Forward", "rare"],
    [8, "Bryan Alceus", "Midfielder", "common"],
    [9, "Danley Jean Plooij", "Forward", "common"],
    [10, "Duckens Nazon", "Forward", "epic"],
    [11, "Frantzdy Pierrot", "Forward", "legendary"],
    [12, "Carnejy Antoine", "Forward", "rare"],
    [13, "Steeven Sabbat", "Midfielder", "common"],
    [14, "Martin Experience", "Defender", "common"],
    [15, "Josué Duverger", "Goalkeeper", "common"],
  ],
  paraguay: [
    [1, "Anthony Silva", "Goalkeeper", "rare"],
    [2, "Robert Rojas", "Defender", "common"],
    [3, "Gustavo Gómez", "Defender", "epic"],
    [4, "Miguel Almirón", "Midfielder", "legendary"],
    [5, "Júnior Alonso", "Defender", "rare"],
    [6, "Mathías Rojas", "Midfielder", "rare"],
    [7, "Antonio Sanabria", "Forward", "epic"],
    [8, "Diego Gómez", "Midfielder", "common"],
    [9, "Gabriel Avalos", "Forward", "rare"],
    [10, "Óscar Romero", "Midfielder", "epic"],
    [11, "Ángel Romero", "Forward", "rare"],
    [12, "Blas Riveros", "Defender", "common"],
    [13, "Iván Ramírez", "Defender", "common"],
    [14, "Matías Rojas", "Midfielder", "common"],
    [15, "Santiago Rojas", "Goalkeeper", "common"],
  ],
  australia: [
    [1, "Mathew Ryan", "Goalkeeper", "epic"],
    [2, "Fran Karačić", "Defender", "common"],
    [3, "Harry Souttar", "Defender", "rare"],
    [4, "Jackson Irvine", "Midfielder", "epic"],
    [5, "Bailey Wright", "Defender", "common"],
    [6, "Mathew Leckie", "Forward", "rare"],
    [7, "Riley McGree", "Midfielder", "common"],
    [8, "Ajdin Hrustić", "Midfielder", "rare"],
    [9, "Mitchell Duke", "Forward", "rare"],
    [10, "Craig Goodwin", "Forward", "epic"],
    [11, "Garang Kuol", "Forward", "common"],
    [12, "Aziz Behich", "Defender", "common"],
    [13, "Keanu Baccus", "Midfielder", "common"],
    [14, "Kusini Yengi", "Forward", "common"],
    [15, "Lawrence Thomas", "Goalkeeper", "common"],
  ],
  turkiye: [
    [1, "Uğurcan Çakır", "Goalkeeper", "rare"],
    [2, "Zeki Çelik", "Defender", "rare"],
    [3, "Merih Demiral", "Defender", "epic"],
    [4, "Hakan Çalhanoğlu", "Midfielder", "legendary"],
    [5, "Çağlar Söyüncü", "Defender", "rare"],
    [6, "Arda Güler", "Midfielder", "epic"],
    [7, "Cengiz Ünder", "Forward", "rare"],
    [8, "İrfan Can Kahveci", "Midfielder", "rare"],
    [9, "Kenan Yıldız", "Forward", "epic"],
    [10, "Burak Yılmaz", "Forward", "legendary"],
    [11, "Kerem Aktürkoğlu", "Forward", "rare"],
    [12, "Ferdi Kadıoğlu", "Defender", "common"],
    [13, "Orkun Kökçü", "Midfielder", "rare"],
    [14, "Abdülkerim Bardakcı", "Defender", "common"],
    [15, "Altay Bayındır", "Goalkeeper", "common"],
  ],
  ecuador: [
    [1, "Hernán Galíndez", "Goalkeeper", "rare"],
    [2, "Angelo Preciado", "Defender", "common"],
    [3, "Piero Hincapié", "Defender", "epic"],
    [4, "Moisés Caicedo", "Midfielder", "legendary"],
    [5, "Felix Torres", "Defender", "rare"],
    [6, "Enner Valencia", "Forward", "legendary"],
    [7, "Carlos Gruezo", "Midfielder", "rare"],
    [8, "Jeremy Sarmiento", "Midfielder", "common"],
    [9, "Jordy Caicedo", "Forward", "rare"],
    [10, "Gonzalo Plata", "Forward", "epic"],
    [11, "Michael Estrada", "Forward", "common"],
    [12, "Pervis Estupiñán", "Defender", "epic"],
    [13, "Kendry Páez", "Midfielder", "rare"],
    [14, "Alan Franco", "Midfielder", "common"],
    [15, "Alexander Domínguez", "Goalkeeper", "common"],
  ],
  ivory_coast: [
    [1, "Badra Ali Sangaré", "Goalkeeper", "rare"],
    [2, "Serge Aurier", "Defender", "epic"],
    [3, "Eric Bailly", "Defender", "rare"],
    [4, "Franck Kessié", "Midfielder", "legendary"],
    [5, "Wilfried Zaha", "Forward", "epic"],
    [6, "Sébastien Haller", "Forward", "epic"],
    [7, "Nicolas Pépé", "Forward", "legendary"],
    [8, "Ibrahim Sangaré", "Midfielder", "rare"],
    [9, "Jean-Philippe Krasso", "Forward", "rare"],
    [10, "Simon Adingra", "Forward", "epic"],
    [11, "Christian Atsu", "Midfielder", "common"],
    [12, "Ghislain Konan", "Defender", "common"],
    [13, "Max-Alain Gradel", "Forward", "rare"],
    [14, "Jean-Daniel Akpa Akpro", "Midfielder", "common"],
    [15, "Yahia Fofana", "Goalkeeper", "common"],
  ],
  curacao: [
    [1, "Eloy Room", "Goalkeeper", "rare"],
    [2, "Cuco Martina", "Defender", "epic"],
    [3, "Juriën Gaari", "Defender", "common"],
    [4, "Leandro Bacuna", "Midfielder", "epic"],
    [5, "Sherel Floranus", "Defender", "rare"],
    [6, "Roly Bonevacia", "Midfielder", "common"],
    [7, "Elson Hooi", "Forward", "rare"],
    [8, "Gino Jelvardi", "Midfielder", "common"],
    [9, "Jarchinio Antonia", "Forward", "rare"],
    [10, "Brandley Kuwas", "Forward", "epic"],
    [11, "Rangelo Janga", "Forward", "legendary"],
    [12, "Tyrick Mitchell", "Defender", "common"],
    [13, "Shanon Carmelia", "Forward", "common"],
    [14, "Juninho Bacuna", "Midfielder", "rare"],
    [15, "Trevor Doornbusch", "Goalkeeper", "common"],
  ],
  tunisia: [
    [1, "Aymen Dahmen", "Goalkeeper", "rare"],
    [2, "Wajdi Kechrida", "Defender", "common"],
    [3, "Yassine Meriah", "Defender", "rare"],
    [4, "Ellyes Skhiri", "Midfielder", "epic"],
    [5, "Montassar Talbi", "Defender", "rare"],
    [6, "Aïssa Laïdouni", "Midfielder", "common"],
    [7, "Youssef Msakni", "Forward", "epic"],
    [8, "Hamza Rafia", "Midfielder", "common"],
    [9, "Issam Jebali", "Forward", "rare"],
    [10, "Wahbi Khazri", "Forward", "legendary"],
    [11, "Hamza Lahmar", "Forward", "common"],
    [12, "Ali Maaloul", "Defender", "rare"],
    [13, "Naim Sliti", "Forward", "rare"],
    [14, "Ghailene Chaalali", "Midfielder", "common"],
    [15, "Bechir Ben Said", "Goalkeeper", "common"],
  ],
  sweden: [
    [1, "Robin Olsen", "Goalkeeper", "rare"],
    [2, "Victor Lindelöf", "Defender", "epic"],
    [3, "Pontus Jansson", "Defender", "rare"],
    [4, "Emil Forsberg", "Midfielder", "epic"],
    [5, "Filip Helander", "Defender", "common"],
    [6, "Dejan Kulusevski", "Midfielder", "legendary"],
    [7, "Alexander Isak", "Forward", "legendary"],
    [8, "Mattias Svanberg", "Midfielder", "rare"],
    [9, "Viktor Gyökeres", "Forward", "epic"],
    [10, "Marcus Berg", "Forward", "rare"],
    [11, "Jesper Karlsson", "Forward", "rare"],
    [12, "Ludwig Augustinsson", "Defender", "common"],
    [13, "Kristoffer Olsson", "Midfielder", "common"],
    [14, "Emil Holm", "Defender", "common"],
    [15, "Karl-Johan Johnsson", "Goalkeeper", "common"],
  ],
  iran: [
    [1, "Alireza Beiranvand", "Goalkeeper", "rare"],
    [2, "Hossein Kanaani", "Defender", "common"],
    [3, "Rouzbeh Cheshmi", "Defender", "rare"],
    [4, "Saeid Ezatolahi", "Midfielder", "epic"],
    [5, "Milad Mohammadi", "Defender", "rare"],
    [6, "Mehdi Taremi", "Forward", "legendary"],
    [7, "Alireza Jahanbakhsh", "Forward", "epic"],
    [8, "Saman Ghoddos", "Midfielder", "common"],
    [9, "Mehdi Ghayedi", "Forward", "rare"],
    [10, "Sardar Azmoun", "Forward", "legendary"],
    [11, "Omid Noorafkan", "Midfielder", "common"],
    [12, "Ehsan Hajsafi", "Defender", "rare"],
    [13, "Karim Ansarifard", "Forward", "rare"],
    [14, "Vahid Amiri", "Midfielder", "common"],
    [15, "Hossein Hosseini", "Goalkeeper", "common"],
  ],
  egypt: [
    [1, "Mohamed El Shenawy", "Goalkeeper", "epic"],
    [2, "Mohamed Hany", "Defender", "common"],
    [3, "Mohamed Abdelmonem", "Defender", "rare"],
    [4, "Mohamed Elneny", "Midfielder", "epic"],
    [5, "Ahmed Hegazi", "Defender", "rare"],
    [6, "Mohamed Salah", "Forward", "legendary"],
    [7, "Omar Marmoush", "Forward", "epic"],
    [8, "Trézéguet", "Forward", "rare"],
    [9, "Mostafa Mohamed", "Forward", "rare"],
    [10, "Emam Ashour", "Midfielder", "common"],
    [11, "Marwan Hamdy", "Forward", "common"],
    [12, "Ahmed Sayed Zizo", "Midfielder", "rare"],
    [13, "Hamdy Fathy", "Midfielder", "common"],
    [14, "Ayman Ashraf", "Defender", "common"],
    [15, "Mohamed Abou Gabal", "Goalkeeper", "common"],
  ],
  new_zealand: [
    [1, "Oliver Sail", "Goalkeeper", "rare"],
    [2, "Liberato Cacace", "Defender", "epic"],
    [3, "Bill Tuiloma", "Defender", "common"],
    [4, "Joe Bell", "Midfielder", "rare"],
    [5, "Nando Pijanker", "Defender", "common"],
    [6, "Ryan Thomas", "Midfielder", "epic"],
    [7, "Marco Rojas", "Midfielder", "legendary"],
    [8, "Marko Stamenić", "Midfielder", "common"],
    [9, "Chris Wood", "Forward", "legendary"],
    [10, "Ben Waine", "Forward", "rare"],
    [11, "Elijah Just", "Midfielder", "common"],
    [12, "Kosta Barbarouses", "Forward", "epic"],
    [13, "Alex Greive", "Forward", "common"],
    [14, "Michael Boxall", "Defender", "rare"],
    [15, "Max Crocombe", "Goalkeeper", "common"],
  ],
  saudi_arabia: [
    [1, "Mohamed Al-Owais", "Goalkeeper", "rare"],
    [2, "Sultan Al-Ghannam", "Defender", "common"],
    [3, "Ali Al-Bulaihi", "Defender", "epic"],
    [4, "Salem Al-Dawsari", "Midfielder", "legendary"],
    [5, "Mohammed Al-Breik", "Defender", "rare"],
    [6, "Sami Al-Najei", "Midfielder", "common"],
    [7, "Saleh Al-Shehri", "Forward", "epic"],
    [8, "Firas Al-Buraikan", "Forward", "rare"],
    [9, "Abdullah Al-Hamdan", "Forward", "common"],
    [10, "Hassan Tambakti", "Defender", "common"],
    [11, "Fahad Al-Muwallad", "Forward", "rare"],
    [12, "Yasir Al-Shahrani", "Defender", "common"],
    [13, "Abdulellah Al-Malki", "Midfielder", "rare"],
    [14, "Yahya Al-Shehri", "Midfielder", "common"],
    [15, "Nawaf Al-Abed", "Forward", "common"],
  ],
  cape_verde: [
    [1, "Vozinha", "Goalkeeper", "rare"],
    [2, "Dylan Tavares", "Defender", "common"],
    [3, "Jójó", "Defender", "rare"],
    [4, "Marco Tavares", "Midfielder", "epic"],
    [5, "Roberto Lopes", "Defender", "rare"],
    [6, "Ryan Mendes", "Forward", "epic"],
    [7, "Jâson", "Forward", "rare"],
    [8, "Patrick Andrade", "Midfielder", "common"],
    [9, "Bébé", "Forward", "legendary"],
    [10, "Gilson Tavares", "Forward", "epic"],
    [11, "Jamiro Monteiro", "Midfielder", "rare"],
    [12, "Diney", "Defender", "common"],
    [13, "Garry Rodrigues", "Forward", "rare"],
    [14, "Platini", "Forward", "common"],
    [15, "Kelvin Pires", "Goalkeeper", "common"],
  ],
  norway: [
    [1, "Bernd Leno", "Goalkeeper", "epic"],
    [2, "Julian Ryerson", "Defender", "rare"],
    [3, "Stefan Strandberg", "Defender", "common"],
    [4, "Martin Ødegaard", "Midfielder", "legendary"],
    [5, "Kristoffer Ajer", "Defender", "rare"],
    [6, "Sander Berge", "Midfielder", "epic"],
    [7, "Erling Haaland", "Forward", "legendary"],
    [8, "Joshua King", "Forward", "rare"],
    [9, "Alexander Sørloth", "Forward", "epic"],
    [10, "Antoine Semenyo", "Forward", "rare"],
    [11, "Aron Dønnum", "Midfielder", "common"],
    [12, "Felix Myhre", "Midfielder", "common"],
    [13, "Patrick Berg", "Midfielder", "rare"],
    [14, "Leo Østigård", "Defender", "common"],
    [15, "André Hansen", "Goalkeeper", "common"],
  ],
  iraq: [
    [1, "Jalal Hassan", "Goalkeeper", "rare"],
    [2, "Ali Adnan", "Defender", "epic"],
    [3, "Ayman Mokhtar", "Defender", "common"],
    [4, "Zidane Iqbal", "Midfielder", "epic"],
    [5, "Hussein Ali", "Defender", "rare"],
    [6, "Amjad Attwan", "Midfielder", "common"],
    [7, "Aymen Hussein", "Forward", "legendary"],
    [8, "Mohammed Ali Ahmed", "Midfielder", "rare"],
    [9, "Mohanad Ali", "Forward", "epic"],
    [10, "Zaid Abdullah", "Midfielder", "common"],
    [11, "Bashar Resan", "Midfielder", "rare"],
    [12, "Saad Rashid", "Midfielder", "common"],
    [13, "Ali Faez", "Defender", "common"],
    [14, "Ahmed Yasin", "Midfielder", "common"],
    [15, "Hussein Hassan", "Goalkeeper", "common"],
  ],
  austria: [
    [1, "Patrick Pentz", "Goalkeeper", "rare"],
    [2, "David Alaba", "Defender", "legendary"],
    [3, "Kevin Wimmer", "Defender", "common"],
    [4, "Marcel Sabitzer", "Midfielder", "epic"],
    [5, "Philipp Lienhart", "Defender", "rare"],
    [6, "Konrad Laimer", "Midfielder", "epic"],
    [7, "Marko Arnautović", "Forward", "legendary"],
    [8, "Christoph Baumgartner", "Midfielder", "rare"],
    [9, "Michael Gregoritsch", "Forward", "rare"],
    [10, "Maximilian Wöber", "Defender", "rare"],
    [11, "Romano Schmid", "Midfielder", "common"],
    [12, "Stefan Posch", "Defender", "rare"],
    [13, "Flavius Daniliuc", "Defender", "common"],
    [14, "Alexander Prass", "Midfielder", "common"],
    [15, "Heinz Lindner", "Goalkeeper", "common"],
  ],
  jordan: [
    [1, "Yazid Abulaila", "Goalkeeper", "rare"],
    [2, "Yazan Al-Naimat", "Defender", "common"],
    [3, "Tareq Shoman", "Defender", "rare"],
    [4, "Rajaei Ayed", "Midfielder", "epic"],
    [5, "Ihsan Haddad", "Defender", "rare"],
    [6, "Mousa Al-Taamari", "Forward", "legendary"],
    [7, "Ali Olwan", "Forward", "epic"],
    [8, "Mahmoud Al-Mardi", "Midfielder", "common"],
    [9, "Yaseen Al-Bakhit", "Forward", "rare"],
    [10, "Nizar Al-Rashdan", "Midfielder", "common"],
    [11, "Ehab Al-Hanbali", "Defender", "common"],
    [12, "Anas Ahmed", "Midfielder", "rare"],
    [13, "Abdallah Nasoub", "Forward", "common"],
    [14, "Baha Abdel-Rahman", "Midfielder", "common"],
    [15, "Ahmad Nawfal", "Goalkeeper", "common"],
  ],
  uzbekistan: [
    [1, "Utkir Yusupov", "Goalkeeper", "rare"],
    [2, "Akramjon Komilov", "Defender", "common"],
    [3, "Egor Krimets", "Defender", "rare"],
    [4, "Jasurbek Jurayev", "Midfielder", "epic"],
    [5, "Azizbek Turgunboev", "Defender", "rare"],
    [6, "Otabek Shukurov", "Midfielder", "common"],
    [7, "Eldor Shomurodov", "Forward", "legendary"],
    [8, "Jaloliddin Masharipov", "Midfielder", "epic"],
    [9, "Igor Sergeev", "Forward", "rare"],
    [10, "Khozhimat Erkinov", "Midfielder", "common"],
    [11, "Abbosbek Fayzullaev", "Midfielder", "rare"],
    [12, "Sanjar Tulyakov", "Defender", "common"],
    [13, "Odil Khamrobekov", "Defender", "rare"],
    [14, "Abdulla Abdullaev", "Midfielder", "common"],
    [15, "Khamza Alakbarov", "Goalkeeper", "common"],
  ],
  dr_congo: [
    [1, "Joël Kiassumbua", "Goalkeeper", "rare"],
    [2, "Chancel Mbemba", "Defender", "epic"],
    [3, "Christian Luyindama", "Defender", "rare"],
    [4, "Edo Kayembe", "Midfielder", "epic"],
    [5, "Marcel Tisserand", "Defender", "common"],
    [6, "Cédric Bakambu", "Forward", "legendary"],
    [7, "Théo Bongonda", "Forward", "rare"],
    [8, "Gaël Kakuta", "Midfielder", "epic"],
    [9, "Fiston Mayele", "Forward", "rare"],
    [10, "Yoane Wissa", "Forward", "epic"],
    [11, "Aaron Tchombani", "Midfielder", "common"],
    [12, "Arthur Masuaku", "Defender", "rare"],
    [13, "Paul-José Mpoku", "Midfielder", "common"],
    [14, "Chadrac Akolo", "Forward", "common"],
    [15, "Brady Fleury", "Goalkeeper", "common"],
  ],
  panama: [
    [1, "Jaime Penedo", "Goalkeeper", "rare"],
    [2, "Michael Murillo", "Defender", "epic"],
    [3, "Fidel Escobar", "Defender", "common"],
    [4, "Aníbal Godoy", "Midfielder", "epic"],
    [5, "Román Torres", "Defender", "rare"],
    [6, "Adalberto Carrasquilla", "Midfielder", "rare"],
    [7, "José Fajardo", "Forward", "common"],
    [8, "Alberto Quintero", "Midfielder", "rare"],
    [9, "Gabriel Torres", "Forward", "epic"],
    [10, "Luis Mejía", "Goalkeeper", "common"],
    [11, "Rolando Blackburn", "Forward", "legendary"],
    [12, "César Blackman", "Midfielder", "common"],
    [13, "Ismael Díaz", "Forward", "rare"],
    [14, "Harold Cummings", "Defender", "common"],
    [15, "Orlando Mosquera", "Goalkeeper", "common"],
  ],
  ghana: [
    [1, "Lawrence Ati-Zigi", "Goalkeeper", "rare"],
    [2, "Gideon Mensah", "Defender", "common"],
    [3, "Daniel Amartey", "Defender", "rare"],
    [4, "Thomas Partey", "Midfielder", "legendary"],
    [5, "Alexander Djiku", "Defender", "epic"],
    [6, "Mohammed Kudus", "Midfielder", "epic"],
    [7, "Jordan Ayew", "Forward", "rare"],
    [8, "André Ayew", "Forward", "legendary"],
    [9, "Inaki Williams", "Forward", "epic"],
    [10, "Antoine Semenyo", "Forward", "rare"],
    [11, "Kamaldeen Sulemana", "Forward", "rare"],
    [12, "Salis Abdul Samed", "Midfielder", "common"],
    [13, "Ernest Nuamah", "Forward", "common"],
    [14, "Alidu Seidu", "Defender", "common"],
    [15, "Richard Ofori", "Goalkeeper", "common"],
  ],
};
