/** Canonical squads from generate_seed_data.py SQUADS block. */
export const CORE = {
  mexico: [
    [1, "Guillermo Ochoa", "Goalkeeper", "rare"],
    [2, "Jorge Sánchez", "Defender", "common"],
    [3, "César Montes", "Defender", "rare"],
    [4, "Edson Álvarez", "Midfielder", "epic"],
    [5, "Héctor Moreno", "Defender", "common"],
    [6, "Andrés Guardado", "Midfielder", "epic"],
    [7, "Raúl Jiménez", "Forward", "legendary"],
    [8, "Carlos Rodríguez", "Midfielder", "common"],
    [9, "Henry Martín", "Forward", "rare"],
    [10, "Alexis Vega", "Forward", "rare"],
    [11, "Uriel Antuna", "Forward", "common"],
    [12, "Orbelín Pineda", "Midfielder", "common"],
    [13, "Luis Chávez", "Midfielder", "rare"],
    [14, "Santiago Giménez", "Forward", "epic"],
    [15, "Rodolfo Cota", "Goalkeeper", "common"],
  ],
  argentina: [
    [1, "Emiliano Martínez", "Goalkeeper", "epic"],
    [2, "Nahuel Molina", "Defender", "rare"],
    [3, "Nicolás Otamendi", "Defender", "rare"],
    [4, "Enzo Fernández", "Midfielder", "epic"],
    [5, "Leandro Paredes", "Midfielder", "common"],
    [6, "Rodrigo De Paul", "Midfielder", "epic"],
    [7, "Ángel Di María", "Forward", "legendary"],
    [8, "Alexis Mac Allister", "Midfielder", "rare"],
    [9, "Julián Álvarez", "Forward", "epic"],
    [10, "Lionel Messi", "Forward", "legendary"],
    [11, "Lautaro Martínez", "Forward", "epic"],
    [12, "Giovani Lo Celso", "Midfielder", "common"],
    [13, "Cristian Romero", "Defender", "rare"],
    [14, "Exequiel Palacios", "Midfielder", "common"],
    [15, "Gerónimo Rulli", "Goalkeeper", "common"],
  ],
  brazil: [
    [1, "Alisson", "Goalkeeper", "epic"],
    [2, "Danilo", "Defender", "rare"],
    [3, "Marquinhos", "Defender", "epic"],
    [4, "Casemiro", "Midfielder", "epic"],
    [5, "Fabinho", "Midfielder", "rare"],
    [6, "Bruno Guimarães", "Midfielder", "epic"],
    [7, "Vinícius Júnior", "Forward", "legendary"],
    [8, "Rodrygo", "Forward", "epic"],
    [9, "Richarlison", "Forward", "rare"],
    [10, "Neymar", "Forward", "legendary"],
    [11, "Raphinha", "Forward", "epic"],
    [12, "Alex Sandro", "Defender", "common"],
    [13, "Bremer", "Defender", "rare"],
    [14, "Endrick", "Forward", "rare"],
    [15, "Ederson", "Goalkeeper", "rare"],
  ],
  france: [
    [1, "Mike Maignan", "Goalkeeper", "epic"],
    [2, "Jules Koundé", "Defender", "epic"],
    [3, "Dayot Upamecano", "Defender", "rare"],
    [4, "Aurélien Tchouaméni", "Midfielder", "epic"],
    [5, "William Saliba", "Defender", "epic"],
    [6, "N'Golo Kanté", "Midfielder", "legendary"],
    [7, "Antoine Griezmann", "Forward", "epic"],
    [8, "Adrien Rabiot", "Midfielder", "rare"],
    [9, "Olivier Giroud", "Forward", "rare"],
    [10, "Kylian Mbappé", "Forward", "legendary"],
    [11, "Ousmane Dembélé", "Forward", "epic"],
    [12, "Theo Hernández", "Defender", "rare"],
    [13, "Kingsley Coman", "Forward", "rare"],
    [14, "Warren Zaïre-Emery", "Midfielder", "common"],
    [15, "Alphonse Areola", "Goalkeeper", "common"],
  ],
  england: [
    [1, "Jordan Pickford", "Goalkeeper", "epic"],
    [2, "Kyle Walker", "Defender", "rare"],
    [3, "John Stones", "Defender", "epic"],
    [4, "Declan Rice", "Midfielder", "epic"],
    [5, "Harry Maguire", "Defender", "rare"],
    [6, "Trent Alexander-Arnold", "Defender", "epic"],
    [7, "Bukayo Saka", "Forward", "legendary"],
    [8, "Jude Bellingham", "Midfielder", "legendary"],
    [9, "Harry Kane", "Forward", "legendary"],
    [10, "Phil Foden", "Midfielder", "epic"],
    [11, "Jack Grealish", "Forward", "rare"],
    [12, "Marcus Rashford", "Forward", "rare"],
    [13, "Conor Gallagher", "Midfielder", "common"],
    [14, "Ezri Konsa", "Defender", "common"],
    [15, "Aaron Ramsdale", "Goalkeeper", "common"],
  ],
  germany: [
    [1, "Manuel Neuer", "Goalkeeper", "legendary"],
    [2, "Joshua Kimmich", "Midfielder", "epic"],
    [3, "Antonio Rüdiger", "Defender", "epic"],
    [4, "İlkay Gündoğan", "Midfielder", "epic"],
    [5, "Jonathan Tah", "Defender", "rare"],
    [6, "Jamal Musiala", "Midfielder", "legendary"],
    [7, "Kai Havertz", "Forward", "epic"],
    [8, "Leon Goretzka", "Midfielder", "rare"],
    [9, "Niclas Füllkrug", "Forward", "rare"],
    [10, "Florian Wirtz", "Midfielder", "legendary"],
    [11, "Leroy Sané", "Forward", "epic"],
    [12, "David Raum", "Defender", "common"],
    [13, "Thomas Müller", "Forward", "epic"],
    [14, "Nico Schlotterbeck", "Defender", "common"],
    [15, "Marc-André ter Stegen", "Goalkeeper", "rare"],
  ],
  spain: [
    [1, "Unai Simón", "Goalkeeper", "epic"],
    [2, "Dani Carvajal", "Defender", "epic"],
    [3, "Aymeric Laporte", "Defender", "rare"],
    [4, "Rodri", "Midfielder", "legendary"],
    [5, "Pau Torres", "Defender", "rare"],
    [6, "Gavi", "Midfielder", "epic"],
    [7, "Álvaro Morata", "Forward", "rare"],
    [8, "Pedri", "Midfielder", "legendary"],
    [9, "Joselu", "Forward", "common"],
    [10, "Lamine Yamal", "Forward", "legendary"],
    [11, "Ferran Torres", "Forward", "rare"],
    [12, "Nico Williams", "Forward", "epic"],
    [13, "Mikel Oyarzabal", "Forward", "rare"],
    [14, "Fabián Ruiz", "Midfielder", "common"],
    [15, "David Raya", "Goalkeeper", "rare"],
  ],
  portugal: [
    [1, "Diogo Costa", "Goalkeeper", "epic"],
    [2, "João Cancelo", "Defender", "epic"],
    [3, "Rúben Dias", "Defender", "epic"],
    [4, "Bruno Fernandes", "Midfielder", "legendary"],
    [5, "Pepe", "Defender", "rare"],
    [6, "João Palhinha", "Midfielder", "rare"],
    [7, "Cristiano Ronaldo", "Forward", "legendary"],
    [8, "Bernardo Silva", "Midfielder", "epic"],
    [9, "Gonçalo Ramos", "Forward", "rare"],
    [10, "Pedro Neto", "Forward", "epic"],
    [11, "Rafael Leão", "Forward", "epic"],
    [12, "Nuno Mendes", "Defender", "rare"],
    [13, "Vitinha", "Midfielder", "common"],
    [14, "Otávio", "Midfielder", "common"],
    [15, "José Sá", "Goalkeeper", "common"],
  ],
  united_states: [
    [1, "Matt Turner", "Goalkeeper", "rare"],
    [2, "Sergiño Dest", "Defender", "rare"],
    [3, "Walker Zimmerman", "Defender", "common"],
    [4, "Tyler Adams", "Midfielder", "epic"],
    [5, "Antonee Robinson", "Defender", "rare"],
    [6, "Yunus Musah", "Midfielder", "rare"],
    [7, "Giovanni Reyna", "Midfielder", "epic"],
    [8, "Weston McKennie", "Midfielder", "rare"],
    [9, "Christian Pulisic", "Forward", "legendary"],
    [10, "Gio Reyna", "Midfielder", "epic"],
    [11, "Timothy Weah", "Forward", "rare"],
    [12, "Folarin Balogun", "Forward", "rare"],
    [13, "Ricardo Pepi", "Forward", "common"],
    [14, "Brenden Aaronson", "Midfielder", "common"],
    [15, "Ethan Horvath", "Goalkeeper", "common"],
  ],
  canada: [
    [1, "Milan Borjan", "Goalkeeper", "rare"],
    [2, "Alphonso Davies", "Defender", "legendary"],
    [3, "Steven Vitória", "Defender", "common"],
    [4, "Sam Adekugbe", "Defender", "common"],
    [5, "Alistair Johnston", "Defender", "rare"],
    [6, "Stephen Eustáquio", "Midfielder", "epic"],
    [7, "Tajon Buchanan", "Forward", "rare"],
    [8, "Jonathan David", "Forward", "legendary"],
    [9, "Cyle Larin", "Forward", "rare"],
    [10, "Junior Hoilett", "Forward", "common"],
    [11, "Liam Millar", "Forward", "common"],
    [12, "Ismaël Koné", "Midfielder", "rare"],
    [13, "Mark-Anthony Kaye", "Midfielder", "common"],
    [14, "Lucas Cavallini", "Forward", "common"],
    [15, "Maxime Crépeau", "Goalkeeper", "common"],
  ],
};
