#!/usr/bin/env python3
"""
Keep Android, Cloud Functions, Firebase config, and seed JSON in sync.
Reads project.config.json (single source of truth) and validates / generates artifacts.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONFIG_PATH = ROOT / "project.config.json"


def load_config() -> dict:
    with CONFIG_PATH.open(encoding="utf-8") as f:
        return json.load(f)


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def fail(msg: str) -> None:
    print(f"ERROR: {msg}", file=sys.stderr)
    sys.exit(1)


def ok(msg: str) -> None:
    print(f"  OK: {msg}")


def check_contains(path: Path, needle: str, label: str) -> None:
    if not path.exists():
        fail(f"Missing {label}: {path}")
    if needle not in read_text(path):
        fail(f"{label} ({path}) missing expected value: {needle}")
    ok(f"{label} → {needle}")


def sync_seed_files(config: dict) -> None:
    android = ROOT / config["seed"]["android"]
    functions = ROOT / config["seed"]["functions"]
    names = [
        "teams_seed.json",
        "players_seed.json",
        "stickers_seed.json",
        "slot_symbols_seed.json",
    ]
    for name in names:
        a, f = android / name, functions / name
        if not a.exists() or not f.exists():
            fail(f"Seed file missing: {name}. Run: python3 scripts/generate_seed_data.py")
        if a.read_bytes() != f.read_bytes():
            fail(f"Seed out of sync: {name}. Run: python3 scripts/generate_seed_data.py")
        ok(f"seed identical: {name}")


def generate_functions_project_config(config: dict) -> None:
    fb = config["firebase"]
    dc = config["dataConnect"]
    game = config["game"]
    em = config["emulators"]
    out = ROOT / "functions" / "src" / "projectConfig.ts"
    content = f"""// AUTO-GENERATED by scripts/sync_project.py — do not edit by hand.
// Source: project.config.json

export const PROJECT_ID = "{fb['projectId']}";
export const FUNCTIONS_REGION = "{fb['functionsRegion']}";
export const ANDROID_PACKAGE = "{fb['androidPackage']}";

export const DATA_CONNECT_SERVICE_ID = "{dc['serviceId']}";
export const DATA_CONNECT_LOCATION = "{dc['location']}";
export const DATA_CONNECT_INSTANCE_ID = "{dc['instanceId']}";
export const DATA_CONNECT_DATABASE = "{dc['database']}";

export const STICKERS_PER_PACK = {game['stickersPerPack']};
export const SIGNUP_FREE_PACKS = {game['signupFreePacks']};
export const LOGIN_REWARD_PACKS = {game['loginRewardPacks']};
export const LOGIN_REWARD_INTERVAL_HOURS = {game['loginRewardIntervalHours']};
export const REWARDED_AD_STICKERS = {game['rewardedAdStickers']};
export const REWARDED_AD_COOLDOWN_MINUTES = {game['rewardedAdCooldownMinutes']};
export const DAILY_FREE_PACKS = {game['dailyFreePacks']};
export const DAILY_REWARDED_PACK_LIMIT = {game['dailyRewardedPackLimit']};
export const DAILY_FREE_SLOT_SPINS = {game['dailyFreeSlotSpins']};
export const REWARDED_SLOT_SPINS = {game['rewardedSlotSpins']};
export const REWARDED_SLOT_SPIN_COOLDOWN_MINUTES = {game['rewardedSlotSpinCooldownMinutes']};
export const DAILY_SLOT_PACK_REWARD_CAP = {game['dailySlotPackRewardCap']};
export const SWAP_DUPLICATES_FOR_PACK = {game['swapDuplicatesForPack']};
export const TOTAL_TEAMS = {game['totalTeams']};
export const PLAYERS_PER_TEAM = {game['playersPerTeam']};
export const TOTAL_STICKERS = {game['totalStickers']};

export const EMULATOR_PORTS = {{
  auth: {em['auth']},
  functions: {em['functions']},
  firestore: {em['firestore']},
  storage: {em['storage']},
  dataconnect: {em['dataconnect']},
}} as const;
"""
    out.write_text(content, encoding="utf-8")
    ok(f"generated {out.relative_to(ROOT)}")


def generate_android_project_config_kt(config: dict) -> None:
    fb = config["firebase"]
    dc = config["dataConnect"]
    em = config["emulators"]
    out = ROOT / "android/app/src/main/java/com/techmomentum/wc2026/config/ProjectConfig.kt"
    out.parent.mkdir(parents=True, exist_ok=True)
    content = f"""package com.techmomentum.wc2026.config

import com.techmomentum.wc2026.BuildConfig

/**
 * Single access point for project-wide constants (synced via [project.config.json]).
 * Regenerate / validate: `./scripts/sync_project.sh`
 */
object ProjectConfig {{
    const val FIREBASE_PROJECT_ID = BuildConfig.FIREBASE_PROJECT_ID
    const val ANDROID_PACKAGE = BuildConfig.ANDROID_PACKAGE
    const val FUNCTIONS_REGION = BuildConfig.FUNCTIONS_REGION
    const val STORAGE_BUCKET = BuildConfig.STORAGE_BUCKET

    const val DATA_CONNECT_SERVICE_ID = BuildConfig.DATA_CONNECT_SERVICE_ID
    const val DATA_CONNECT_LOCATION = BuildConfig.DATA_CONNECT_LOCATION
    const val DATA_CONNECT_INSTANCE_ID = BuildConfig.DATA_CONNECT_INSTANCE_ID
    const val DATA_CONNECT_DATABASE = BuildConfig.DATA_CONNECT_DATABASE

    const val EMULATOR_AUTH_PORT = BuildConfig.EMULATOR_AUTH_PORT
    const val EMULATOR_FUNCTIONS_PORT = BuildConfig.EMULATOR_FUNCTIONS_PORT
    const val EMULATOR_FIRESTORE_PORT = BuildConfig.EMULATOR_FIRESTORE_PORT
    const val EMULATOR_STORAGE_PORT = BuildConfig.EMULATOR_STORAGE_PORT
    const val EMULATOR_DATA_CONNECT_PORT = BuildConfig.EMULATOR_DATA_CONNECT_PORT

    const val GCP_PUBLIC_PROJECT_ID = BuildConfig.GCP_PUBLIC_PROJECT_ID
    const val FIREBASE_PROJECT_NUMBER = BuildConfig.FIREBASE_PROJECT_NUMBER
    const val GOOGLE_WEB_CLIENT_ID = BuildConfig.GOOGLE_WEB_CLIENT_ID
    val GOOGLE_SIGN_IN_ENABLED: Boolean = BuildConfig.GOOGLE_SIGN_IN_ENABLED

    // Documented in project.config.json — keep GameConstants.kt in sync
    const val EXPECTED_PROJECT_ID = "{fb['projectId']}"
    const val EXPECTED_ANDROID_PACKAGE = "{fb['androidPackage']}"
}}
"""
    out.write_text(content, encoding="utf-8")
    ok(f"generated {out.relative_to(ROOT)}")


def validate_repo(config: dict) -> None:
    fb = config["firebase"]
    dc = config["dataConnect"]

    print("==> Validating Firebase project binding")
    check_contains(ROOT / ".firebaserc", fb["projectId"], ".firebaserc")
    check_contains(ROOT / "dataconnect/dataconnect.yaml", dc["serviceId"], "dataconnect.yaml serviceId")
    check_contains(ROOT / "dataconnect/dataconnect.yaml", dc["location"], "dataconnect.yaml location")
    check_contains(ROOT / "dataconnect/dataconnect.yaml", dc["instanceId"], "dataconnect.yaml instanceId")
    check_contains(ROOT / "dataconnect/dataconnect.yaml", dc["database"], "dataconnect.yaml database")

    gs = ROOT / "android/app/google-services.json"
    check_contains(gs, fb["projectId"], "google-services.json project_id")
    check_contains(gs, fb["androidPackage"], "google-services.json package_name")
    if fb["storageBucket"] not in read_text(gs):
        fail(f"google-services.json storage_bucket should contain {fb['storageBucket']}")

    connector = ROOT / "dataconnect/connector/default/connector.yaml"
    check_contains(connector, dc["kotlinPackage"], "connector.yaml package")
    check_contains(connector, "kotlinSdk", "connector.yaml kotlinSdk")

    print("==> Syncing seed JSON (Android ↔ Functions)")
    sync_seed_files(config)


def validate_game_constants(config: dict) -> None:
    print("==> Validating game constants (Functions projectConfig)")
    pc_ts = read_text(ROOT / "functions/src/projectConfig.ts")
    for name, key in [
        ("STICKERS_PER_PACK", "stickersPerPack"),
        ("LOGIN_REWARD_PACKS", "loginRewardPacks"),
        ("REWARDED_AD_STICKERS", "rewardedAdStickers"),
        ("DAILY_FREE_PACKS", "dailyFreePacks"),
        ("REWARDED_SLOT_SPINS", "rewardedSlotSpins"),
    ]:
        val = config["game"][key]
        if f"export const {name} = {val};" not in pc_ts:
            fail(f"functions/src/projectConfig.ts: expected {name} = {val}")
    ok("game constants match project.config.json")


def main() -> None:
    if not CONFIG_PATH.exists():
        fail(f"Missing {CONFIG_PATH}")
    config = load_config()
    print(f"==> Syncing {config['name']}")
    print(f"    Config: {CONFIG_PATH.relative_to(ROOT)}")
    validate_repo(config)
    print("==> Generating synced source files")
    generate_functions_project_config(config)
    generate_android_project_config_kt(config)
    validate_game_constants(config)
    print("")
    print("==> Project sync complete")
    print("    Next: cd android && ./gradlew assembleDebug")
    print("    Firebase: replace android/app/google-services.json if still placeholder")


if __name__ == "__main__":
    main()
